# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            EclipseSHOE
tagline:          
url:              https://gitkrax.github.io/epshoe/
paginate:         1
baseurl:          https://gitkrax.github.io/epshoe/
author:
  name:           Jonne Arjoranta
  url:            jonne.arjoranta.fi
  email:          jonne.arjoranta@gmail.com

# Custom vars
version:          0.0.1
github:
repo:             https://github.com/gitkrax/epshoe

# Page list for the page navigation
pages_list:
        About: '/epshoe/about'
        Scenarios: '/epshoe/scenarios'
        Feed: '/epshoe/atom.xml/'
        
# Collections
collections:
    scenarios:
        output: true
