# Permalinks
permalink:        pretty

# Setup
title:            EclipseSHOE
tagline:          
url:              https://gitkrax.github.io/epshoe/
paginate:         3
pagination_path:  page:num # makes pages sub/page2/index.html, sub/page3/index.html, etc
baseurl:          /epshoe
author:
  name:           Jonne Arjoranta
  url:            jonne.arjoranta.fi
  email:          jonne.arjoranta@gmail.com

# Custom vars
version:          0.0.1
github:
repo:             https://github.com/gitkrax/epshoe

# Page list for the page navigation
pages_list:
        About: '/about'
        Scenarios: '/scenarios'
        Archive: '/archive'
        Feed: '/atom.xml'
        
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "scenarios" # previously `post` in Jekyll 2.2.
    values:
      layout: "article"
        
# Collections
collections:
    scenarios:
        output: true

# Prose configurations
prose:
  media: 'assets/images'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
